services:
    website:
        image: nginx
        container_name: website
        volumes:
            - /Users/ayobamishittu/Desktop/ayo/website/html:/usr/share/nginx/html
        ports:
            - 80:80
        restart: always
